# Generated by Django 5.2.3 on 2025-06-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('DishName', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
