# Generated by Django 5.2.3 on 2025-06-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.CharField(max_length=50)),
                ('items', models.CharField(max_length=500)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
    ]
