# Generated by Django 5.2.3 on 2025-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staff_staffattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Rice', 'Rice'), ('Thali', 'Thali'), ('Main Course', 'Main Course'), ('Beverage', 'Beverage')], default='Main Course', max_length=20),
        ),
    ]
