# Generated by Django 5.2.4 on 2025-07-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_invoice_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Rice', 'Rice'), ('Thali', 'Thali'), ('Main Course', 'Main Course'), ('Additional', 'Additional')], default='Main Course', max_length=20),
        ),
    ]
