# Generated by Django 5.2.4 on 2025-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.CharField(choices=[('Sura', 'Sura'), ('Vijay', 'Vijay'), ('Swad', 'Swad'), ('Aditya', 'Aditya')], max_length=10)),
            ],
        ),
    ]
