# Generated by Django 5.2.4 on 2025-08-15 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='expense',
            name='owner',
            field=models.CharField(choices=[('Sura', 'Sura'), ('Vijay', 'Vijay'), ('Swad', 'Swad'), ('Aditya', 'Aditya')], default='Swad', max_length=10),
        ),
    ]
