# Generated by Django 5.2.4 on 2025-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_expense_date_alter_expense_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', max_length=10),
        ),
    ]
